### PR TITLE
Remove external reexports

### PR DESCRIPTION
**Pull request by hauleth**
You should not reexport external dependencies unless it is meta-repository.

### CODE REVIEW

**Comment by mitchmindtree** [comment]
Thanks! I left a reply [here](https://en.reddit.com/r/rust/comments/3o6q59/daggy_an_indexable_directed_acyclic_graph_dag/cvveird) with some thoughts, would be interested to hear your thoughts before merging!

**Comment by hauleth** [comment]
Firstly in most cases you do not need that reexports. You won't create `EdgeIndex` by yourself. You will get it via calls to `Dag::add_edge` or something. Then you do not need to import it anyway, so there is no gain.

**Comment by hellow554** [comment]
I think this should not be merged, because my understanding is (please correct me if I'm wrong!), that if you want to use Petgraphs functions you would need to have petgraph as an external dependency in the correct version (!), but if you reexport it, I just can use the one daggy provides for me.
Am I correct?

**Comment by mitchmindtree** [comment]
Closing due to age, and because I think the re-export is worth keeping.

**Pull request closed without merging**
